# Generated by Django 5.1.5 on 2025-02-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображение товаров'},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='product_title_9e36ed_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
